### ISSUE TITLE
Updating to latest KubeJS breaks KubeJS-UI

### ISSUE THREAD

**Issue by dkraemer** [KubeJS-Mods/KubeJS-UI#9]
Hi!

When using KubeJS-UI 1802.1.7 with KubeJS 1802.5.4 Minecraft crashes on start.

### Versions ###
* Forge: 40.1.25
* KubeJS-UI: kubejs-ui-forge-1802.1.7-build.13
* KubeJS (last known good): kubejs-forge-1802.5.3-build.467
* KubeJS (crashing): kubejs-forge-1802.5.4-build.474

### Exit message ###
```"java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/text/Text"```

### UI code ###
``` 
onEvent("ui.main_menu", (event) => {
  event.replace((ui) => {
    ui.fillBackground("ui:textures/bg.png", 1920, 1080);
  });
});
```
### Error log ###
```
[23:09:12] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering overlay
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:886) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/text/Text
	at net.minecraft.Util.m_137559_(Util.java:210) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.m_91239_(Minecraft.java:624) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.Util.m_137521_(Util.java:395) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.LoadingOverlay.handler$zed000$onRender(LoadingOverlay.java:602) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	... 16 more
Caused by: java.lang.NoClassDefFoundError: dev/latvian/mods/kubejs/text/Text
	at dev.latvian.kubejs.ui.widget.Widget.<init>(Widget.java:56) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.widget.Panel.<init>(Panel.java:17) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.widget.UI.<init>(UI.java:30) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.ScreenKubeJSUI.<init>(ScreenKubeJSUI.java:40) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.KubeJSUIEventHandler.openGui(KubeJSUIEventHandler.java:38) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:132) ~[architectury-4.4.68.jar%2356!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler_212_EventHandlerImplClient_event_ScreenOpenEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:907) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.LoadingOverlay.handler$zed000$onRender(LoadingOverlay.java:600) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: dev.latvian.mods.kubejs.text.Text
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at dev.latvian.kubejs.ui.widget.Widget.<init>(Widget.java:56) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.widget.Panel.<init>(Panel.java:17) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.widget.UI.<init>(UI.java:30) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.ScreenKubeJSUI.<init>(ScreenKubeJSUI.java:40) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.latvian.kubejs.ui.KubeJSUIEventHandler.openGui(KubeJSUIEventHandler.java:38) ~[kubejs-ui-forge-1802.1.7-build.13.jar%23109!/:1802.1.7-build.13]
	at dev.architectury.event.forge.EventHandlerImplClient.event(EventHandlerImplClient.java:132) ~[architectury-4.4.68.jar%2356!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler_212_EventHandlerImplClient_event_ScreenOpenEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:907) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:561) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.LoadingOverlay.handler$zed000$onRender(LoadingOverlay.java:600) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
	... 16 more
[23:09:12] [Render thread/FATAL]: Preparing crash report with UUID
```

**Comment by MaxNeedsSnacks** [comment]
Yep, that's on me, I did a code search with GitHub to verify no mods use the `Text` class, and this didn't turn up :upside_down_face:

**Comment by MaxNeedsSnacks** [comment]
Ho boy, I can't get a dev environment with KubeJS working right now... I'll hopefully have a solution pushed by tomorrow tho ^^
